// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2

import (
	"fmt"
	"gustavocoutino.compilador/internal/ops"
	"gustavocoutino.compilador/internal/quadruples"
	"gustavocoutino.compilador/internal/semantics"
	"gustavocoutino.compilador/internal/types"
	"os"
	"strconv"
)

//line parser.y:15
type yySymType struct {
	yys      int
	entero   int
	flotante float64
	texto    string
	tipo     types.Tipo
}

const ID = 57346
const LITERAL = 57347
const CTE_ENT = 57348
const CTE_FLOT = 57349
const PROGRAMA = 57350
const INICIO = 57351
const FIN = 57352
const VARS = 57353
const ENTERO = 57354
const FLOTANTE = 57355
const NULA = 57356
const RETORNO = 57357
const SI = 57358
const SINO = 57359
const MIENTRAS = 57360
const HAZ = 57361
const ESCRIBE = 57362
const MAS = 57363
const MENOS = 57364
const POR = 57365
const ENTRE = 57366
const MAYOR = 57367
const MENOR = 57368
const IGUAL = 57369
const DIFERENTE = 57370
const ASIGNAVAR = 57371
const COMA = 57372
const PCOMA = 57373
const DOSPUNTOS = 57374
const LPARENTESIS = 57375
const RPARENTESIS = 57376
const LLLAVE = 57377
const RLLAVE = 57378
const LCORCHETE = 57379
const RCORCHETE = 57380

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ID",
	"LITERAL",
	"CTE_ENT",
	"CTE_FLOT",
	"PROGRAMA",
	"INICIO",
	"FIN",
	"VARS",
	"ENTERO",
	"FLOTANTE",
	"NULA",
	"RETORNO",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"MAS",
	"MENOS",
	"POR",
	"ENTRE",
	"MAYOR",
	"MENOR",
	"IGUAL",
	"DIFERENTE",
	"ASIGNAVAR",
	"COMA",
	"PCOMA",
	"DOSPUNTOS",
	"LPARENTESIS",
	"RPARENTESIS",
	"LLLAVE",
	"RLLAVE",
	"LCORCHETE",
	"RCORCHETE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:146

// Lexer es una representacion de un analizador lexico.
// Lexer contiene el indice del caracter actual de la entrada de caracteres,
// el indice del caracter leido, la entrada de caracteres, y el caracter
// actual
type Lexer struct {
	input        string
	position     int
	readPosition int
	ch           byte
}

// Lista de palabras reservadas
var palabrasReservadas = map[string]int{
	"programa": PROGRAMA,
	"inicio":   INICIO,
	"fin":      FIN,
	"vars":     VARS,
	"entero":   ENTERO,
	"flotante": FLOTANTE,
	"nula":     NULA,
	"si":       SI,
	"sino":     SINO,
	"mientras": MIENTRAS,
	"haz":      HAZ,
	"escribe":  ESCRIBE,
	"retorno":  RETORNO,
}

// Lex es invocada por el parser para realizar el
// analisis lexico de la entrada
func (l *Lexer) Lex(lval *yySymType) int {
	return l.Next(lval)
}

// Next analiza el siguiente token en la entrada de
// caracteres usando las expresiones regulares y la lista
// de simbolos terminales de la gramatica
func (l *Lexer) Next(lval *yySymType) int {
	l.skipWhitespace()
	if l.ch == 0 {
		return 0
	}
	switch l.ch {
	default:
		if isLetter(l.ch) {
			token := l.readIdentifier()
			if tipo, esReservada := palabrasReservadas[token]; esReservada {
				return tipo
			}
			lval.texto = token
			return ID
		} else if isDigit(l.ch) {
			return l.readNumber(lval)
		} else {
			l.Error(fmt.Sprintf("Carácter no reconocido: %c", l.ch))
		}
	case '+':
		l.readChar()
		return MAS
	case '-':
		l.readChar()
		return MENOS
	case '*':
		l.readChar()
		return POR
	case '/':
		l.readChar()
		return ENTRE
	case '>':
		l.readChar()
		return MAYOR
	case '<':
		l.readChar()
		return MENOR
	case ',':
		l.readChar()
		return COMA
	case ';':
		l.readChar()
		return PCOMA
	case ':':
		l.readChar()
		return DOSPUNTOS
	case '(':
		l.readChar()
		return LPARENTESIS
	case ')':
		l.readChar()
		return RPARENTESIS
	case '{':
		l.readChar()
		return LLLAVE
	case '}':
		l.readChar()
		return RLLAVE
	case '[':
		l.readChar()
		return LCORCHETE
	case ']':
		l.readChar()
		return RCORCHETE
	case '=':
		l.readChar()
		if l.ch == '=' {
			l.readChar()
			return IGUAL
		} else {
			return ASIGNAVAR
		}
	case '!':
		l.readChar()
		if l.ch == '=' {
			l.readChar()
			return DIFERENTE
		} else {
			l.Error(fmt.Sprintf("Carácter no reconocido: %c", l.ch))
		}
	case '"':
		position := l.position
		l.readChar()
		for isLetter(l.ch) || isDigit(l.ch) || isWhitespace(l.ch) || isOther(l.ch) {
			l.readChar()
		}
		if l.ch == '"' {
			lval.texto = l.input[position:l.position]
			l.readChar()
			return LITERAL
		}
		l.Error(fmt.Sprint("Formato de literal incorrecto"))
	}
	return 0
}

// readIdentifier lee el identificador y regresa
// dicho id
func (l *Lexer) readIdentifier() string {
	position := l.position
	for isLetter(l.ch) || isDigit(l.ch) || l.ch == '_' || l.ch == '-' {
		l.readChar()

	}
	return l.input[position:l.position]
}

// readNumber lee un numero de acuerdo a las expresiones
// regulares definidas y regresa este numero. Este numero puede ser un entero
// o un flotante, y este flotante puede estar escrito en
// notacion cientifica
func (l *Lexer) readNumber(lval *yySymType) int {
	position := l.position
	for isDigit(l.ch) {
		l.readChar()
	}

	if l.ch == '.' && isDigit(l.peekChar()) {
		l.readChar()
		for isDigit(l.ch) {
			l.readChar()
		}
		if l.ch == 'e' {
			if l.peekChar() == '+' || l.peekChar() == '-' {
				l.readChar()
				l.readChar()
				if !isDigit(l.ch) {
					l.Error("Notación científica inválida: se esperaban dígitos después del exponente")
				}
				for isDigit(l.ch) {
					l.readChar()
				}
			} else {
				l.Error("Notación científica inválida: se esperaban un carácter '+' o '-' despues del exponente")
			}
		}
		valor, _ := strconv.ParseFloat(l.input[position:l.position], 64)
		lval.flotante = valor
		return CTE_FLOT
	}
	valor, _ := strconv.Atoi(l.input[position:l.position])
	lval.entero = valor
	return CTE_ENT
}

// readChar lee el siguiente caracter.
// Actualiza la posicion actual de la entrada de
// caracteres, y la posicion del caracter actual leido
func (l *Lexer) readChar() {
	if l.readPosition >= len(l.input) {
		l.ch = 0
	} else {
		l.ch = l.input[l.readPosition]
	}
	l.position = l.readPosition
	l.readPosition += 1
}

// peekChar ve el siguiente caracter sin
// consumirlo, para distinguir tokens de dos
// caracteres como '==' o '!=', o detectar
// el punto decimal de un flotante
func (l *Lexer) peekChar() byte {
	if l.readPosition >= len(l.input) {
		return 0
	} else {
		return l.input[l.readPosition]
	}
}

// isLetter revisa si el caracter se encuentra entre la
// a y z (no distingue entre mayusculas y minisculas)
func isLetter(ch byte) bool {
	return 'a' <= ch && ch <= 'z' || 'A' <= ch && ch <= 'Z'
}

// isDigit revisa si el caracter es un numero
func isDigit(ch byte) bool {
	return ch >= '0' && ch <= '9'
}

// isWhitespace revisa si el caracter es un espacio en blanco
func isWhitespace(ch byte) bool {
	return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r'
}

// isOther revisa si el caracter es un símbolo permitido dentro de un literal
// (puntuación o signos comunes distintos de la comilla doble)
func isOther(ch byte) bool {
	switch ch {
	case '-', '_', '=', '?', '.', ',', ';', ':', '!', '@', '#', '$',
		'%', '^', '&', '*', '(', ')', '+', '/', '<', '>',
		'[', ']', '{', '}', '|', '\\', '~', '\'', '`':
		return true
	}
	return false
}

// skipWhitespace se salta los espacios en blanco y avanza el lexer
func (l *Lexer) skipWhitespace() {
	for l.ch == ' ' || l.ch == '\t' || l.ch == '\n' || l.ch == '\r' {
		l.readChar()
	}
}

// Error es la implementacion del método de error
// de la interfaz de Lexer para imprimir un error
// del Lexer propio o del Parser (que tiene la misma interfaz)
func (l *Lexer) Error(s string) {
	fmt.Fprintln(os.Stderr, "Error de sintaxis:", s)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Porfavor provee el nombre de un archivo")
		return
	}
	fileName := os.Args[1]
	data, err := os.ReadFile(fileName)
	if err != nil {
		fmt.Println("Error al leer el archivo:", err)
		return
	}
	lexer := &Lexer{input: string(data), position: 0, readPosition: 0}
	lexer.readChar()
	ok := yyParse(lexer)
	if ok == 0 {
		if semantics.HasError() {
			fmt.Println("El análisis semántico tiene errores")
			os.Exit(1)
		}
		fmt.Println("Compilación exitosa")
	} else if ok == 1 {
		fmt.Println("El análisis léxico contiene errores")
	} else if ok == 2 {
		fmt.Println("Agotamiento de memoria")
	}
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 181

var yyAct = [...]uint8{
	14, 70, 22, 30, 6, 65, 84, 85, 63, 67,
	64, 35, 21, 43, 23, 119, 10, 125, 118, 43,
	109, 108, 106, 75, 48, 44, 56, 45, 32, 46,
	48, 44, 39, 45, 55, 46, 59, 58, 56, 57,
	31, 8, 145, 76, 25, 27, 47, 87, 144, 39,
	141, 142, 47, 139, 136, 121, 62, 43, 71, 61,
	73, 74, 39, 77, 80, 81, 82, 112, 48, 44,
	43, 45, 88, 46, 99, 68, 69, 104, 100, 102,
	54, 48, 44, 52, 45, 138, 46, 66, 4, 34,
	47, 71, 86, 73, 74, 111, 124, 107, 33, 113,
	91, 92, 19, 47, 93, 94, 95, 96, 68, 69,
	134, 123, 97, 98, 29, 122, 91, 92, 126, 2,
	66, 26, 129, 130, 131, 127, 128, 135, 11, 16,
	17, 16, 17, 15, 143, 137, 53, 140, 101, 39,
	73, 74, 51, 24, 21, 3, 146, 79, 78, 110,
	83, 133, 72, 117, 116, 115, 114, 90, 105, 60,
	89, 42, 41, 40, 38, 37, 36, 132, 120, 50,
	103, 49, 28, 20, 18, 12, 7, 9, 5, 1,
	13,
}

var yyPact = [...]int16{
	111, -1000, 141, 57, -1000, 30, -1000, -1000, -19, 119,
	140, -21, -1000, 139, -1000, -1000, -1000, -1000, 8, -1000,
	13, -1000, 104, -1000, 7, -1000, -1000, 117, 68, -1000,
	53, 138, 52, 132, -1000, -1000, -1000, -1000, -1000, 49,
	-1000, -1000, -1000, 5, 6, 4, 3, 66, 54, -11,
	-1000, 11, -1000, -1000, -1000, 54, 54, 54, 54, 87,
	9, -1000, -1000, 79, 89, -1000, 54, -1000, 134, 134,
	-1000, -7, -1000, -1000, -1000, -1000, 117, -1000, -12, 67,
	-1000, -13, -14, 65, -1000, -1000, -1000, -1000, -1000, 36,
	54, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -16,
	-1000, -1000, -1000, -20, -1000, 24, -1000, 54, -21, 77,
	-17, 87, -1000, 95, 54, 54, 54, 54, -1000, 30,
	-1000, -1000, -1000, 93, -21, 23, -1000, 89, 89, -1000,
	-1000, -1000, 55, 22, -21, 19, -1000, 15, 130, -1000,
	-1000, -1000, 17, 10, -1000, 117, -1000,
}

var yyPgo = [...]uint8{
	0, 0, 180, 179, 178, 4, 177, 2, 176, 175,
	174, 102, 173, 172, 3, 11, 171, 170, 169, 168,
	167, 166, 165, 164, 1, 163, 162, 161, 7, 160,
	159, 158, 8, 157, 156, 10, 155, 154, 5, 153,
	9, 152, 151, 150, 149, 6, 148, 147,
}

var yyR1 = [...]int8{
	0, 4, 3, 5, 5, 6, 6, 8, 10, 10,
	11, 12, 13, 13, 1, 1, 7, 14, 14, 17,
	9, 2, 2, 16, 16, 19, 18, 20, 20, 15,
	15, 15, 15, 15, 15, 15, 29, 27, 26, 30,
	30, 31, 21, 28, 28, 33, 33, 33, 33, 34,
	32, 36, 32, 32, 37, 35, 39, 35, 35, 38,
	38, 38, 38, 38, 40, 40, 41, 41, 22, 42,
	42, 23, 44, 25, 43, 43, 45, 45, 24, 46,
	46, 47, 47,
}

var yyR2 = [...]int8{
	0, 0, 9, 1, 0, 2, 0, 4, 1, 2,
	4, 2, 3, 0, 1, 1, 3, 2, 0, 0,
	11, 1, 1, 1, 0, 0, 5, 5, 0, 1,
	1, 1, 2, 1, 1, 1, 0, 4, 3, 2,
	1, 0, 5, 1, 3, 1, 1, 1, 1, 0,
	4, 0, 4, 1, 0, 4, 0, 4, 1, 3,
	1, 2, 2, 1, 1, 1, 1, 1, 7, 2,
	0, 7, 0, 6, 1, 3, 1, 1, 4, 1,
	0, 1, 3,
}

var yyChk = [...]int16{
	-1000, -3, 8, 4, 31, -4, -5, -8, 11, -6,
	35, 9, -9, -2, -1, 14, 12, 13, -10, -11,
	-12, 4, -7, 35, 4, 36, -11, 32, -13, 10,
	-14, 33, -1, 30, 36, -15, -21, -22, -23, -24,
	-25, -26, -27, 4, 16, 18, 20, 37, 15, -16,
	-18, 4, 31, 4, 31, 29, 33, 33, 33, 33,
	-30, -15, -28, -32, -35, -38, 33, -40, 21, 22,
	-24, 4, -41, 6, 7, 34, 32, -28, -46, -47,
	-28, -28, -28, -43, -45, -28, 5, 38, -15, -29,
	-33, 21, 22, 25, 26, 27, 28, 23, 24, -28,
	-40, 4, -40, -17, -1, -31, 34, 30, 34, 34,
	-44, 30, 31, -32, -34, -36, -37, -39, 34, 35,
	-19, 31, -28, -7, 19, 34, -45, -35, -35, -38,
	-38, -5, -20, -42, 17, -7, 31, -14, 30, 31,
	-7, 31, 36, 4, 31, 32, -1,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 1, 4, 6, 3, 0, 0,
	0, 0, 5, 0, 21, 22, 14, 15, 0, 8,
	0, 13, 0, 18, 0, 7, 9, 0, 11, 2,
	0, 24, 0, 0, 16, 17, 29, 30, 31, 0,
	33, 34, 35, 0, 0, 0, 0, 0, 0, 0,
	23, 0, 10, 12, 32, 0, 80, 0, 0, 0,
	0, 40, 36, 43, 53, 58, 0, 60, 0, 0,
	63, 64, 65, 66, 67, 19, 0, 41, 0, 79,
	81, 0, 0, 72, 74, 76, 77, 38, 39, 0,
	0, 49, 51, 45, 46, 47, 48, 54, 56, 0,
	61, 64, 62, 0, 25, 0, 78, 0, 0, 0,
	0, 0, 37, 44, 0, 0, 0, 0, 59, 4,
	28, 42, 82, 70, 0, 0, 75, 50, 52, 55,
	57, 18, 26, 0, 0, 0, 73, 0, 0, 68,
	69, 71, 0, 0, 20, 0, 27,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:42
		{
			semantics.IniciarPrograma(yyDollar[2].texto)
		}
	case 2:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:44
		{
			semantics.ImprimirTablaVariablesGlobal()
			semantics.ImprimirDirectorioFunciones()
			quadruples.ImprimirCuadruplos()
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:53
		{
			semantics.DeclararIdsActuales(yyDollar[3].tipo)
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:56
		{
			semantics.AgregarIdActual(yyDollar[1].texto)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:59
		{
			semantics.AgregarIdActual(yyDollar[3].texto)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:62
		{
			yyVAL.tipo = types.TipoEntero
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:62
		{
			yyVAL.tipo = types.TipoFlotante
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:65
		{
			semantics.IniciarFuncionConParametros(yyDollar[2].texto, yyDollar[1].tipo)
		}
	case 20:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser.y:67
		{
			semantics.TerminarFuncion()
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:70
		{
			yyVAL.tipo = types.TipoNula
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:74
		{
			semantics.AgregarParametroActual(yyDollar[1].texto, yyDollar[3].tipo)
		}
	case 27:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:77
		{
			semantics.AgregarParametroActual(yyDollar[3].texto, yyDollar[5].tipo)
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:81
		{
			quadruples.GenerarRetornoCuadruplo()
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:86
		{
			quadruples.GenerarAsignaCuadruplo(yyDollar[1].texto)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:89
		{
			quadruples.GenerarCuadruplo()
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:92
		{
			quadruples.EmpujarOperador(ops.MAYOR)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:94
		{
			quadruples.EmpujarOperador(ops.MENOR)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:96
		{
			quadruples.EmpujarOperador(ops.IGUAL)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:98
		{
			quadruples.EmpujarOperador(ops.DIFERENTE)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:101
		{
			quadruples.EmpujarOperador(ops.MAS)
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:103
		{
			quadruples.GenerarCuadruplo()
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:105
		{
			quadruples.EmpujarOperador(ops.MAS)
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:107
		{
			quadruples.GenerarCuadruplo()
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:110
		{
			quadruples.EmpujarOperador(ops.POR)
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:112
		{
			quadruples.GenerarCuadruplo()
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:114
		{
			quadruples.EmpujarOperador(ops.ENTRE)
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:116
		{
			quadruples.GenerarCuadruplo()
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:120
		{
			if variable, existe := semantics.BuscarVariable(yyDollar[1].texto); existe {
				quadruples.EmpujarOperando(variable.Direccion, variable.Tipo)
			} else {
				semantics.ErrorSemantico(fmt.Sprintf("variable '%s' no declarada", yyDollar[1].texto))
			}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:127
		{
			direccion, tipo := semantics.ProcesarConstante(strconv.Itoa(yyDollar[1].entero), types.TipoEntero)
			quadruples.EmpujarOperando(direccion, tipo)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:130
		{
			direccion, tipo := semantics.ProcesarConstante(strconv.FormatFloat(yyDollar[1].flotante, 'g', -1, 64), types.TipoFlotante)
			quadruples.EmpujarOperando(direccion, tipo)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:137
		{
			quadruples.GenerarEscribeCuadruplo()
		}
	}
	goto yystack /* stack new state and value */
}
