// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2

import (
	"fmt"
	"gustavocoutino.compilador/internal/semantics"
	"gustavocoutino.compilador/internal/types"
	"os"
	"strconv"
)

//line parser.y:13
type yySymType struct {
	yys      int
	entero   int
	flotante float64
	texto    string
	tipo     types.Tipo
}

const ID = 57346
const LITERAL = 57347
const CTE_ENT = 57348
const CTE_FLOT = 57349
const PROGRAMA = 57350
const INICIO = 57351
const FIN = 57352
const VARS = 57353
const ENTERO = 57354
const FLOTANTE = 57355
const NULA = 57356
const RETORNO = 57357
const SI = 57358
const SINO = 57359
const MIENTRAS = 57360
const HAZ = 57361
const ESCRIBE = 57362
const MAS = 57363
const MENOS = 57364
const POR = 57365
const ENTRE = 57366
const MAYOR = 57367
const MENOR = 57368
const IGUAL = 57369
const DIFERENTE = 57370
const ASIGNAVAR = 57371
const COMA = 57372
const PCOMA = 57373
const DOSPUNTOS = 57374
const LPARENTESIS = 57375
const RPARENTESIS = 57376
const LLLAVE = 57377
const RLLAVE = 57378
const LCORCHETE = 57379
const RCORCHETE = 57380

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ID",
	"LITERAL",
	"CTE_ENT",
	"CTE_FLOT",
	"PROGRAMA",
	"INICIO",
	"FIN",
	"VARS",
	"ENTERO",
	"FLOTANTE",
	"NULA",
	"RETORNO",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"MAS",
	"MENOS",
	"POR",
	"ENTRE",
	"MAYOR",
	"MENOR",
	"IGUAL",
	"DIFERENTE",
	"ASIGNAVAR",
	"COMA",
	"PCOMA",
	"DOSPUNTOS",
	"LPARENTESIS",
	"RPARENTESIS",
	"LLLAVE",
	"RLLAVE",
	"LCORCHETE",
	"RCORCHETE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:97

// Lexer es una representacion de un analizador lexico.
// Lexer contiene el indice del caracter actual de la entrada de caracteres,
// el indice del caracter leido, la entrada de caracteres, y el caracter
// actual
type Lexer struct {
	input        string
	position     int
	readPosition int
	ch           byte
}

// Lista de palabras reservadas
var palabrasReservadas = map[string]int{
	"programa": PROGRAMA,
	"inicio":   INICIO,
	"fin":      FIN,
	"vars":     VARS,
	"entero":   ENTERO,
	"flotante": FLOTANTE,
	"nula":     NULA,
	"si":       SI,
	"sino":     SINO,
	"mientras": MIENTRAS,
	"haz":      HAZ,
	"escribe":  ESCRIBE,
	"retorno":  RETORNO,
}

// Lex es invocada por el parser para realizar el
// analisis lexico de la entrada
func (l *Lexer) Lex(lval *yySymType) int {
	return l.Next(lval)
}

// Next analiza el siguiente token en la entrada de
// caracteres usando las expresiones regulares y la lista
// de simbolos terminales de la gramatica
func (l *Lexer) Next(lval *yySymType) int {
	l.skipWhitespace()
	if l.ch == 0 {
		return 0
	}
	switch l.ch {
	default:
		if isLetter(l.ch) {
			token := l.readIdentifier()
			if tipo, esReservada := palabrasReservadas[token]; esReservada {
				return tipo
			}
			lval.texto = token
			return ID
		} else if isDigit(l.ch) {
			return l.readNumber(lval)
		} else {
			l.Error(fmt.Sprintf("Carácter no reconocido: %c", l.ch))
		}
	case '+':
		l.readChar()
		return MAS
	case '-':
		l.readChar()
		return MENOS
	case '*':
		l.readChar()
		return POR
	case '/':
		l.readChar()
		return ENTRE
	case '>':
		l.readChar()
		return MAYOR
	case '<':
		l.readChar()
		return MENOR
	case ',':
		l.readChar()
		return COMA
	case ';':
		l.readChar()
		return PCOMA
	case ':':
		l.readChar()
		return DOSPUNTOS
	case '(':
		l.readChar()
		return LPARENTESIS
	case ')':
		l.readChar()
		return RPARENTESIS
	case '{':
		l.readChar()
		return LLLAVE
	case '}':
		l.readChar()
		return RLLAVE
	case '[':
		l.readChar()
		return LCORCHETE
	case ']':
		l.readChar()
		return RCORCHETE
	case '=':
		l.readChar()
		if l.ch == '=' {
			l.readChar()
			return IGUAL
		} else {
			return ASIGNAVAR
		}
	case '!':
		l.readChar()
		if l.ch == '=' {
			l.readChar()
			return DIFERENTE
		} else {
			l.Error(fmt.Sprintf("Carácter no reconocido: %c", l.ch))
		}
	case '"':
		position := l.position
		l.readChar()
		for isLetter(l.ch) || isDigit(l.ch) || isWhitespace(l.ch) || isOther(l.ch) {
			l.readChar()
		}
		if l.ch == '"' {
			lval.texto = l.input[position:l.position]
			l.readChar()
			return LITERAL
		}
		l.Error(fmt.Sprint("Formato de literal incorrecto"))
	}
	return 0
}

// readIdentifier lee el identificador y regresa
// dicho id
func (l *Lexer) readIdentifier() string {
	position := l.position
	for isLetter(l.ch) || isDigit(l.ch) || l.ch == '_' || l.ch == '-' {
		l.readChar()

	}
	return l.input[position:l.position]
}

// readNumber lee un numero de acuerdo a las expresiones
// regulares definidas y regresa este numero. Este numero puede ser un entero
// o un flotante, y este flotante puede estar escrito en
// notacion cientifica
func (l *Lexer) readNumber(lval *yySymType) int {
	position := l.position
	for isDigit(l.ch) {
		l.readChar()
	}

	if l.ch == '.' && isDigit(l.peekChar()) {
		l.readChar()
		for isDigit(l.ch) {
			l.readChar()
		}
		if l.ch == 'e' {
			if l.peekChar() == '+' || l.peekChar() == '-' {
				l.readChar()
				l.readChar()
				if !isDigit(l.ch) {
					l.Error("Notación científica inválida: se esperaban dígitos después del exponente")
				}
				for isDigit(l.ch) {
					l.readChar()
				}
			} else {
				l.Error("Notación científica inválida: se esperaban un carácter '+' o '-' despues del exponente")
			}
		}
		valor, _ := strconv.ParseFloat(l.input[position:l.position], 64)
		lval.flotante = valor
		return CTE_FLOT
	}
	valor, _ := strconv.Atoi(l.input[position:l.position])
	lval.entero = valor
	return CTE_ENT
}

// readChar lee el siguiente caracter.
// Actualiza la posicion actual de la entrada de
// caracteres, y la posicion del caracter actual leido
func (l *Lexer) readChar() {
	if l.readPosition >= len(l.input) {
		l.ch = 0
	} else {
		l.ch = l.input[l.readPosition]
	}
	l.position = l.readPosition
	l.readPosition += 1
}

// peekChar ve el siguiente caracter sin
// consumirlo, para distinguir tokens de dos
// caracteres como '==' o '!=', o detectar
// el punto decimal de un flotante
func (l *Lexer) peekChar() byte {
	if l.readPosition >= len(l.input) {
		return 0
	} else {
		return l.input[l.readPosition]
	}
}

// isLetter revisa si el caracter se encuentra entre la
// a y z (no distingue entre mayusculas y minisculas)
func isLetter(ch byte) bool {
	return 'a' <= ch && ch <= 'z' || 'A' <= ch && ch <= 'Z'
}

// isDigit revisa si el caracter es un numero
func isDigit(ch byte) bool {
	return ch >= '0' && ch <= '9'
}

// isWhitespace revisa si el caracter es un espacio en blanco
func isWhitespace(ch byte) bool {
	return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r'
}

// isOther revisa si el caracter es un símbolo permitido dentro de un literal
// (puntuación o signos comunes distintos de la comilla doble)
func isOther(ch byte) bool {
	switch ch {
	case '-', '_', '=', '?', '.', ',', ';', ':', '!', '@', '#', '$',
		'%', '^', '&', '*', '(', ')', '+', '/', '<', '>',
		'[', ']', '{', '}', '|', '\\', '~', '\'', '`':
		return true
	}
	return false
}

// skipWhitespace se salta los espacios en blanco y avanza el lexer
func (l *Lexer) skipWhitespace() {
	for l.ch == ' ' || l.ch == '\t' || l.ch == '\n' || l.ch == '\r' {
		l.readChar()
	}
}

// Error es la implementacion del método de error
// de la interfaz de Lexer para imprimir un error
// del Lexer propio o del Parser (que tiene la misma interfaz)
func (l *Lexer) Error(s string) {
	fmt.Fprintln(os.Stderr, "Error de sintaxis:", s)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Porfavor provee el nombre de un archivo")
		return
	}
	fileName := os.Args[1]
	data, err := os.ReadFile(fileName)
	if err != nil {
		fmt.Println("Error al leer el archivo:", err)
		return
	}
	lexer := &Lexer{input: string(data), position: 0, readPosition: 0}
	lexer.readChar()
	ok := yyParse(lexer)
	if ok == 0 {
		fmt.Println("El análisis léxico fue exitoso")
		if semantics.HasError() {
			fmt.Println("El análisis semántico tiene errores")
		}
	} else if ok == 1 {
		fmt.Println("El análisis léxico contiene errores")
	} else if ok == 2 {
		fmt.Println("Agotamiento de memoria")
	}
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 173

var yyAct = [...]uint8{
	13, 69, 21, 29, 5, 83, 64, 84, 63, 66,
	34, 62, 42, 22, 117, 20, 110, 9, 42, 116,
	109, 108, 107, 47, 43, 105, 44, 31, 45, 47,
	43, 38, 44, 74, 45, 54, 55, 58, 57, 55,
	56, 137, 42, 30, 75, 46, 86, 24, 38, 26,
	134, 46, 136, 47, 43, 61, 44, 60, 45, 133,
	131, 38, 76, 79, 80, 81, 122, 104, 88, 42,
	87, 53, 51, 98, 33, 46, 103, 99, 101, 4,
	47, 43, 130, 44, 106, 45, 32, 121, 70, 85,
	72, 73, 96, 97, 70, 18, 72, 73, 127, 112,
	113, 111, 46, 114, 115, 67, 68, 90, 91, 7,
	120, 67, 68, 25, 119, 10, 123, 65, 15, 16,
	14, 28, 124, 65, 128, 15, 16, 2, 129, 135,
	132, 38, 52, 50, 23, 90, 91, 20, 138, 92,
	93, 94, 95, 100, 3, 72, 73, 78, 77, 82,
	126, 71, 89, 59, 41, 40, 39, 37, 36, 35,
	125, 118, 49, 102, 48, 27, 19, 17, 11, 6,
	8, 1, 12,
}

var yyPact = [...]int16{
	119, -1000, 140, 48, 98, -1000, -1000, -18, 106, 133,
	-22, -1000, 130, -1000, -1000, -1000, -1000, 11, -1000, 17,
	-1000, 111, -1000, 10, -1000, -1000, 113, 56, -1000, 38,
	129, 41, 128, -1000, -1000, -1000, -1000, -1000, 40, -1000,
	-1000, -1000, 6, 7, 5, 4, 65, 90, -1, -1000,
	12, -1000, -1000, -1000, 90, 90, 90, 90, 84, 8,
	-1000, 37, 114, 69, -1000, 90, -1000, 139, 139, -1000,
	3, -1000, -1000, -1000, -1000, 113, 36, -9, 54, -1000,
	-12, -13, -14, -1000, -1000, -1000, -1000, -1000, -1000, 90,
	90, 90, -1000, -1000, -1000, -1000, 90, 90, -15, -1000,
	-1000, -1000, -21, -1000, -1000, -1000, 90, -22, 68, 35,
	84, 86, 69, 69, -1000, -1000, -1000, 98, -1000, -1000,
	81, -22, -1000, -1000, -1000, 52, 29, -22, 28, 14,
	125, -1000, -1000, -1000, 21, 9, -1000, 113, -1000,
}

var yyPgo = [...]uint8{
	0, 0, 172, 171, 4, 170, 2, 169, 168, 167,
	95, 166, 165, 3, 10, 164, 163, 162, 161, 160,
	159, 158, 157, 1, 156, 155, 154, 7, 153, 11,
	152, 8, 6, 9, 151, 150, 149, 5, 148, 147,
}

var yyR1 = [...]int8{
	0, 3, 4, 4, 5, 5, 7, 9, 9, 10,
	11, 12, 12, 1, 1, 6, 13, 13, 16, 8,
	2, 2, 15, 15, 18, 17, 19, 19, 14, 14,
	14, 14, 14, 14, 14, 26, 25, 28, 28, 20,
	27, 27, 30, 30, 30, 30, 29, 29, 29, 31,
	31, 31, 32, 32, 32, 32, 32, 33, 33, 34,
	34, 21, 35, 35, 22, 24, 36, 36, 37, 37,
	23, 38, 38, 39, 39,
}

var yyR2 = [...]int8{
	0, 8, 1, 0, 2, 0, 4, 1, 2, 4,
	2, 3, 0, 1, 1, 3, 2, 0, 0, 11,
	1, 1, 1, 0, 0, 5, 5, 0, 1, 1,
	1, 2, 1, 1, 1, 3, 3, 2, 1, 4,
	1, 3, 1, 1, 1, 1, 3, 3, 1, 3,
	3, 1, 3, 1, 2, 2, 1, 1, 1, 1,
	1, 7, 2, 0, 7, 5, 1, 3, 1, 1,
	4, 1, 0, 1, 3,
}

var yyChk = [...]int16{
	-1000, -3, 8, 4, 31, -4, -7, 11, -5, 35,
	9, -8, -2, -1, 14, 12, 13, -9, -10, -11,
	4, -6, 35, 4, 36, -10, 32, -12, 10, -13,
	33, -1, 30, 36, -14, -20, -21, -22, -23, -24,
	-25, -26, 4, 16, 18, 20, 37, 15, -15, -17,
	4, 31, 4, 31, 29, 33, 33, 33, 33, -28,
	-14, -27, -29, -31, -32, 33, -33, 21, 22, -23,
	4, -34, 6, 7, 34, 32, -27, -38, -39, -27,
	-27, -27, -36, -37, -27, 5, 38, -14, 31, -30,
	21, 22, 25, 26, 27, 28, 23, 24, -27, -33,
	4, -33, -16, -1, 31, 34, 30, 34, 34, 34,
	30, -29, -31, -31, -32, -32, 34, 35, -18, -27,
	-6, 19, 31, -37, -4, -19, -35, 17, -6, -13,
	30, 31, -6, 31, 36, 4, 31, 32, -1,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 3, 5, 2, 0, 0, 0,
	0, 4, 0, 20, 21, 13, 14, 0, 7, 0,
	12, 0, 17, 0, 6, 8, 0, 10, 1, 0,
	23, 0, 0, 15, 16, 28, 29, 30, 0, 32,
	33, 34, 0, 0, 0, 0, 0, 0, 0, 22,
	0, 9, 11, 31, 0, 72, 0, 0, 0, 0,
	38, 0, 40, 48, 51, 0, 53, 0, 0, 56,
	57, 58, 59, 60, 18, 0, 0, 0, 71, 73,
	0, 0, 0, 66, 68, 69, 36, 37, 35, 0,
	0, 0, 42, 43, 44, 45, 0, 0, 0, 54,
	57, 55, 0, 24, 39, 70, 0, 0, 0, 0,
	0, 41, 46, 47, 49, 50, 52, 3, 27, 74,
	63, 0, 65, 67, 17, 25, 0, 0, 0, 0,
	0, 61, 62, 64, 0, 0, 19, 0, 26,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.y:40
		{
			semantics.ImprimirTablaVariablesGlobal()
			semantics.ImprimirDirectorioFunciones()
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:48
		{
			semantics.DeclararIdsActuales(yyDollar[3].tipo)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:51
		{
			semantics.AgregarIdActual(yyDollar[1].texto)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:54
		{
			semantics.AgregarIdActual(yyDollar[3].texto)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:57
		{
			yyVAL.tipo = types.TipoConstante
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:57
		{
			yyVAL.tipo = types.TipoFlotante
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:60
		{
			semantics.IniciarFuncionConParametros(yyDollar[2].texto, yyDollar[1].tipo)
		}
	case 19:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser.y:62
		{
			semantics.TerminarFuncion()
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:65
		{
			yyVAL.tipo = types.TipoNula
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:69
		{
			semantics.AgregarParametroActual(yyDollar[1].texto, yyDollar[3].tipo)
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:72
		{
			semantics.AgregarParametroActual(yyDollar[3].texto, yyDollar[5].tipo)
		}
	}
	goto yystack /* stack new state and value */
}
